version: '3.8'

services:
  activemq:
    image: apache/activemq-artemis
    ports:
      - "8161:8161"
      - "61616:61616"
    volumes: [ "artemis-mq-data:/opt/activemq/conf", "artemis-mq-data:/data/activemq", "artemis-mq-data:/var/log/activemq" ]
    environment:
      ARTEMIS_USER: admin
      ARTEMIS_PASSWORD: admin
volumes:
  artemis-mq-data: